---
title: "WebScraping1"
author: "Sam"
date: "October 27, 2014"
output: html_document
---

```{r}

library(httr)
library(dplyr)
install.packages("XML")
library(XML)

URL <- 'http://www.bbc.com/sport/winter-olympics/2014/medals/countries'

# Get and parse all tables on page
tables <- URL %>% GET() %>%
  content(as = 'parsed') %>%
  readHTMLTable()

# Gather content and parse all tables (only one on this page)
names(tables)
medals <- as.data.frame(tables)

### Clean ###
# Drop unwanted variables
medals

MedalsTable <- tables[]

head(MedalsTable)
summary(MedalsTable)
arrange <- arrange()
```

```{r}

##### GEM Database #####

# Install Foreign for accessing STATA file
install.packages("foreign")
library(foreign)
library(help=foreign)

<<<<<<< HEAD
# Load data locally
dataSPSS<-read.spss("/Users/thierryracaud/Desktop/2010GEMNES.sav", to.data.frame=TRUE)
=======
# Loading NES data locally
dataSPSS<-read.spss("/Users/samdundon/Desktop/2010GEMNES.sav", use.value.labels=TRUE, to.data.frame=TRUE)

# Ordering data by country
dataSPSS2 <- dataSPSS2[order(dataSPSS$)]
>>>>>>> FETCH_HEAD

### Clean ###

head(dataSPSS)
head(dataSPSS)[1,1:387]

##### OECD PISA 2012 ####

# Load data locally from 

# Convert Excel document into CSV  - with Numbers
# Import CSV fileq

# Mutate- run a function on all variables

# Loading APS data locally
dataSPSS2<-read.spss("/Users/samdundon/Desktop/GEM2010APS.sav", use.value.labels=TRUE, to.data.frame=TRUE)

# Ordering data by country
dataSPSS2 <- dataSPSS2[order(dataSPSS2$Country_Name),]


```

```{r}
install.packages("car")
library(car)
data(Prestige)
car::scatterplotMatrix(Prestige)

# Run an OLS log regression
M1 <- lm(prestige ~ education, data = Prestige)

# Obtain simple statistics
summary(M1)

# Find confidence interval for sample
confint(M1)

# Estimating model with categorial (factor) variable
# Check variable class to see when you have a categorial or continuous variable
M2 <- lm(prestige ~ education + type, data = Prestige)

# Summary statistics
summary(M2)

# Using cut to create a categorial (factor) variable

# Plot M2
plot(M2, which = 2)

# Load data
URL <- 'http://www.ats.ucla.edu/stat/data/binary.csv'
Admission <- read.csv(URL)
car::scatterplotMatrix(Admission)

# Create contingency table
xtabs(~admit + rank, data = Admission)

# Logistic regression with GLM
Logit1 <- glm(admit ~ gre + gpa + as.factor(rank), data = Admission, family = 'binomial')

# Obtain confidence intervals
confint(Logit1)
exp(cbind(OddsRatio = coef(Logit1), confint(Logit1)))


# Import GEM 2009 supportive teaching data
setwd('~/Assign2Education/GEMData')

GEM2009 <- read.spss('2009GEMNESMDS.sav', to.data.frame = TRUE)
GEM2010 <- read.spss('2010GEMNES.sav', to.data.frame = TRUE)



```
