---
title: "Draft1"
author: "Sam"
date: "December 11, 2014"
output: html_document
---

#### Quantitative Analysis of the Impact of Education on Entrepreneurship  


**Data Sources**  
To complete a quantitative analysis of the impact of educational factors -- specifically the encouragement of creatitivity, self-sufficiency, and personal initiative  -- on the country-level rate of entrepreneurship, we have drawn on publicly available data from the Global Entrepreneurship Monitor (GEM) National Expert Survey (NES) and Adult Population Survey (APS).  


The Global Entrepreneurship Monitor project is an annual assessment of the entrepreneurial activity, aspirations, and attitudes of individuals across a wide range of countries.  The countries covered have grown from a low of ten to covering 75% of world population and 89% of world GDP by 2013.  The 2001-2010 multi-year APS data base, for example, contains over 1.3 million observations of a total of 85 countries.  This data is often cited in academic research, including reports by the Organisation for Economic Co-operation and Development.    


The NES is structured around nine entrepreneurial framework contitions evaluated by thirty-six experts in each surveyed country.  These nine entrepreneurial framework conditions are included below (a minimum of four experts must be interviewed on each of the framework conditions).  


1. Finance  
2. Government policies  
3. Government programs  
4. Entrepreneurial Education and Training  
5. Research and Development Transfer (R & D)  
6. Commercial and professional infrastructure  
7. Internal Market openness  
8. Physical infrastructure and services  
9. Cultural and social norms  


The APS is a questionnaire distrubuted to a minimum of 2,000 adults in each participating country.  The survey is created by a central GEM team, but the implementation is managed by national teams that compete for the role of implementing the survey.  Experts are chosen based on experience and specialization and are expected to represent the entire country (including urban and rural areas).  


**Data Selection**  


After reviewing the available data, we decided to select the following variables for our analysis.  

Source | Indicator 
-------------|---------------
APS | Rate of Entrepreneurship (Intention, Nascent, Established)
NES | Way of Teaching
APS | Perceived Capabilities
APS | Fear of Failure / Perceived Opportunities
APS | Perceived Opportunities




After looking through the entire 2001-2010 NES data set and considering the nine entrepreneurial conditions, we decided to use this data set to

In order to trace specifically how supportive of one's self-confidence a given education system is, we chose to use one specific item of the GEM [National Experts Survey (NES)](http://www.gemconsortium.org/Data-Collection) as a proxy, namely D01.  

"In my country, teaching in primary and secondary education encourages creativity, self-sufficiency, and personal initiative"


Regarding this statement, the experts surveyed had to state whether it is:  


1 completely false  
2 somewhat false  
3 neither true nor false  
4 somewhat true  
5 completely true  
  
97 do not know  
98 not applicable  

After searching through many potential data sources about education and finding no indicators suitable to trace our causal chain, we were forced to use that one item of a survey however low quality it might be.  

As a matter of fact, there are many reasons for which we should be concerned about that data and its quality.  

First, it was not always collected which makes any measure hard to follow through time, it is only since 2009 and 2011 that the NES was made compulsory.

Second, the National Expert Surveys are very subjective data. For each entrepreneurial framework condition, that is:  



Only four experts per framework condition are consulted in each country participating.  

Third, the collection of data could arguably be improved. Indeed, it is outsourced by GEM Coordination Team to national teams which seem to manage the time allowed for collection poorly ???METHODOLOGY NES REPORT HERE MAIN BIB ??? . The national teams also tend to rely solely on their own personal networks. Which does not guarantee to get the best experts on each topic.  


Fourth, as a result of the flows above mentioned, we observe a lot of variation from year to year up to 0.73 on a scale from 1 to 5, that is up to 14.6% (UK 2007 / UK 2009). Which is far from what one would expect. Indeed, it seems very doubtful to say that the way of teaching in any country varies so much over time. Educational reforms are much more rare and one should on the contrary expect to see much more stability, almost a constant over a decade.


The NES at 9 entrepreneurial framework conditions (4 national experts for each)

to create graphic visualizations of participants' responses to surveys about entrepreneurship in OECD (Organisation for Economic Co-operation and Development) countries. 



##### Dependent Variables: Explaining the Country-level Rate of Entrepreneurship    


We have examined three dimensions of entrepreneurship to prepare for this stage of the project, established entrepreneurship in the country, nascent entrepreneurship (less than three months), and entrepreneurial intention. We will study each of these successively as we may well observe different effects.  

To measure these three dimensions of entrepreneurship, we have used three [Global Entrepreneurship Monitor (GEM)](http://www.gemconsortium.org) indicators:

- Established Business Ownership Rate (Percentage) 
- Nascent Entrepreneurship Rate (Percentage)
- Entrepreneurial intention Rate (Percentage)  


##### Key Explanatory Variable: Degree of Self-esteem Reinforcement within the Education System    


As Inglehart has shown how personal values are shaped before the age of 20, we will try to show how compulsory education (from 6 to 16 years of age) shapes individuals, especially in terms of self-esteem. To do so, we decided to incorporate GEM indicators that relate to self-esteem and confidence. First, we included GEM survey data on the average "perceived capabilities" of an individual (18-64) in a given country to start a business. Second, we included additional GEM data on how the "fear of failure" could deter an average individual (18-64) in a country to become an entrepreneur. Both of these data sets indicate the average percentage for each characteristic at the country-level.  


##### Control Variables: Controlling for Classic Determinants of Entrepreneurship  


To control for the general state of the economy, we included annual GDP Growth from the World Bank [World Development Indicators](http://data.worldbank.org/data-catalog/world-development-indicators) as a control variable in our regression equations.  In addition, we included a GEM indicator called "Perceived Opportunities." For each country, it is the average percentage of individuals who believe there are opportunities to start a business in their area. Since we look at average individual self-esteem in every OECD country, we believe it is appropriate to look at the opportunities perceived by the average 18-64-year-old individual in these countries.

In the future, we may revise this to include lagged GDP growth in recognition of the time taken for governments and individuals to react to the state of the economy, and are planning to include control variables from GEM. Specifically, we intend to control for the classic determinants of entrepreneurship -- economic and structural determinants. To do so, we will add the following nine key entrepreneurship conditions as defined in the GEM [National Experts Survey (NES)](http://www.gemconsortium.org/Data-Collection).   

1. Finance  
2. Government policies  
3. Government programs  
4. Entrepreneurial Education and Training  
5. Research and Development Transfer (R & D)  
6. Commercial and professional infrastructure  
7. Internal Market openness  
8. Physical infrastructure and services  
9. Cultural and social norms  


##### Regressions


The following equations were used to determine the relationship between our dependent and explanatory variables:  


1. $PercentIntention = PercentPerceived(Perceived Capabilities) + Way of Teaching + PercentOpportunities(Perceived Opportunities)$ 

2. $PercentNascent = PercentPerceived + PercentFear*PercentOpportunities + AnnualGDPGrowth$

3. $PercentOwner = PercentPerceived + PercentFear*PercentOpportunities + AnnualGDPGrowth$  

The variables *Percent Fear* and *Percent Opportunities* were included as an interaction term $PercentFear*PercentOpportunities$ because of the design of the survey. PercentFear is: "the Percentage of 18-64 population with positive perceived opportunities who indicate that fear of failure would prevent them from setting up a business."  

<br>
  
  
  
#### Data Collection and Cleaning

To collect the data necessary to run these regression equations, we downloaded *.csv* data from GEM and used the WDI API to obtain the necessary annual GDP growth of OECD Countries.   


**Necessary R Packages**  


The following packages were needed to complete the data collection portion of this assignment:

- repmis  
- tidyr  
- reshape  
- plyr  
- WDI  


**GEM Data**  


GEM data was embedded in an interactive database and was difficult to extract automatically without writing a program. To simplify this process, we downloaded the necessary *.csv* files and saved them in our GitHub repository (to reduce complexity, we deleted the first three unnecessary rows before saving).  We then linked to the RAW version of the files and added the code required to load them from *R*.  The repmis package is required to load these documents from the repository.  


Cleaning the GEM data required deleting unnecessary characters in the year columns, changing the years from columns to rows (changing the data from wide to long), and changing the column names to describe which data was being analyzed.  In the process of doing this we created new data sets for each of these survey questions, which were called C*dataset* (clean followed by the data set name). This was done for each of the six GEM data sets before merging these sets two at a time to create the data set *FinalGEM*.  


For all 33 OECD countries we should have 13 observations, one per year from 2001 to 2013, for each variable. However, there are a few missing values, especially regarding the perceived opportunities for some countries, namely Estonia, Luxembourg and Slovak Republic.