---
title: "EduDataSource"
author: "Sam"
date: "November 29, 2014"
output: html_document
---

```{r echo =FALSE, cache=TRUE, include=FALSE, results='asis', warning=FALSE}

# Set working directory
setwd('~/Assign2Education/')

# Library required packages repmis, ridy, reshape2, and plyr packages
library(plyr)
library(repmis)
library(tidyr)
library(reshape2)
library(foreign)

# Load citation package
pkgs <- c('plyr','repmis', 'tidyr', 'reshape2', 'stargazer', 'Zelig')
repmis::LoadandCite(pkgs, file= 'DataRpackageCitations.bib')

```

```{r echo =FALSE, cache=TRUE, include=FALSE, results='asis', warning=FALSE}


############# Import data from GEM Survey #############

# Import GEM fear of failure data
FearFail <- repmis::source_data("https://raw.githubusercontent.com/SamDund/Assign2Education/master/GEMData/GEM_FearFail.csv", header = TRUE, cache = FALSE) 


# Import GEM estblished entrepreneurship - current owner data
CurrentOwner <- repmis::source_data("https://raw.githubusercontent.com/SamDund/Assign2Education/master/GEMData/GEM_CurrentOwner.csv", header = TRUE, cache = FALSE) 


# Import GEM entrepreneurial intention data
EntreIntention <- repmis::source_data("https://raw.githubusercontent.com/SamDund/Assign2Education/master/GEMData/GEM_EntreIntention.csv", header = TRUE, cache = FALSE) 


# Import GEM nascent entrepreneur data
NascentEntre <- repmis::source_data("https://raw.githubusercontent.com/SamDund/Assign2Education/master/GEMData/GEM_NascentEntre.csv", header = TRUE, cache = FALSE) 


# Import GEM perceived capabilities data
PerceivedCapabilities <- repmis::source_data("https://raw.githubusercontent.com/SamDund/Assign2Education/master/GEMData/GEM_PerceivedCapabilities.csv", header = TRUE, cache = FALSE) 


# Import GEM perceived opportunities data as a proxy for potential control variables
PerceivedOpportunities <- repmis::source_data("https://raw.githubusercontent.com/SamDund/Assign2Education/master/GEMData/PerceivedOpportunities.csv", header = TRUE, cache = FALSE)


# Import 2010GEM supportive teaching data as a proxy for how favourable to self-confidence a given education system is
SupportiveTeaching <- repmis::source_data("https://raw.githubusercontent.com/SamDund/Assign2Education/master/GEMData/GEMAvgIndicators.csv", header = TRUE, cache = FALSE)


############# Import Annual GEM Country Level Data (means) #############

# Import GEM 2009 supportive teaching data
setwd('~/Assign2Education/GEMData')

GEM2001 <- read.spss('2001GEMNES.sav', to.data.frame = TRUE)
GEM2002 <- read.spss('2002GEMNES.sav', to.data.frame = TRUE)
GEM2003 <- read.spss('2003GEMNES.sav', to.data.frame = TRUE)
GEM2004 <- read.spss('2004GEMNES.sav', to.data.frame = TRUE)
GEM2005 <- read.spss('2005GEMNES.sav', to.data.frame = TRUE)
GEM2006 <- read.spss('2006GEMNES.sav', to.data.frame = TRUE)
GEM2007 <- read.spss('2007GEMNES.sav', to.data.frame = TRUE)
GEM2008 <- read.spss('2008GEMNES.sav', to.data.frame = TRUE)
GEM2009 <- read.spss('2009GEMNESMDS.sav', to.data.frame = TRUE)
GEM2010 <- read.spss('2010GEMNES.sav', to.data.frame = TRUE)



##################### Clean GEM Survey Data  ###################

### Clean FearFail ###
# Question: Percentage of 18-64 population with positive perceived opportunities who indicate that fear of failure would prevent them from setting up a business.

# Remove X's in FearFail year columns
names(FearFail) <- gsub("X", "", names(FearFail))


# Change years from columns to rows and create CFearFail
CFearFail <- melt(data = FearFail,
                  id.vars = c("Country"),
                  measure.vars = c("2001", "2002", "2003", "2004", "2005", "2006",
                                   "2007", "2008", "2009", "2010", "2011", "2012",
                                   "2013"))


# Rename columns
CFearFail <- plyr::rename(x = CFearFail, 
                                      replace = c("variable" = "Year",
                                                  "value" = "PercentFear"))

### Clean CurrentOwner ###
# Question: Percentage of 18-64 population who are currently owner-manager of an established business, i.e., owning and managing a running business that has paid sallaries, wages, or any other payments to the owners for more than 42 months


# Remove X's in CurrentOwner year columns
names(CurrentOwner) <- gsub("X", "", names(CurrentOwner))


# Change years from columns to rows and create CCurrentOwner
CCurrentOwner <- melt(data = CurrentOwner,
                  id.vars = c("Country"),
                  measure.vars = c("2001", "2002", "2003", "2004", "2005", "2006",
                                   "2007", "2008", "2009", "2010", "2011", "2012",
                                   "2013"))


# Rename columns
CCurrentOwner <- plyr::rename(x = CCurrentOwner, 
                                      replace = c("variable" = "Year",
                                                  "value" = "PercentOwner"))


### Clean EntreIntention ###
# Percentage of 18-64 population (individuals involved in any stage of entrepenerurial activity excluded) who intend to start a business within three years.

# Remove X's in EntreIntention year columns
names(EntreIntention) <- gsub("X", "", names(EntreIntention))


# Change years from columns to rows and create CEntreIntention (No 2001 data available)
CEntreIntention <- melt(data = EntreIntention,
                  id.vars = c("Country"),
                  measure.vars = c("2002", "2003", "2004", "2005", "2006",
                                   "2007", "2008", "2009", "2010", "2011", "2012",
                                   "2013"))


# Rename columns
CEntreIntention <- plyr::rename(x = CEntreIntention, 
                                      replace = c("variable" = "Year",
                                                  "value" = "PercentIntention"))


### Clean NascentEntre ###
# Percentage of 18-64 population who are currently a nascent entrepreneur, i.e., actively involved in setting up a business they will own or co-own; this business has not paid salaries, wages, or any other payments to the owners for more than three months.

# Remove X's in NascentEntre year columns
names(NascentEntre) <- gsub("X", "", names(NascentEntre))


# Change years from columns to rows and create CNascentEntre
CNascentEntre <- melt(data = NascentEntre,
                  id.vars = c("Country"),
                  measure.vars = c("2001", "2002", "2003", "2004", "2005", "2006",
                                   "2007", "2008", "2009", "2010", "2011", "2012",
                                   "2013"))


# Rename columns
CNascentEntre <- plyr::rename(x = CNascentEntre, 
                                      replace = c("variable" = "Year",
                                                  "value" = "PercentNascent"))

### Clean PerceivedCapabilities ###
# Percentage of 18-64 population who believe to have the required skills and knowledge to start a business


# Remove X's in PerceivedCapabilities year columns
names(PerceivedCapabilities) <- gsub("X", "", names(PerceivedCapabilities))


# Change years from columns to rows and create CPreceivedCapabilities
CPerceivedCapabilities<- melt(data = PerceivedCapabilities,
                  id.vars = c("Country"),
                  measure.vars = c("2001", "2002", "2003", "2004", "2005", "2006",
                                   "2007", "2008", "2009", "2010", "2011", "2012",
                                   "2013"))


# Rename columns
CPerceivedCapabilities <- plyr::rename(x = CPerceivedCapabilities, 
                                      replace = c("variable" = "Year",
                                                  "value" = "PercentPerceived"))


### Clean PerceivedOpportunities ###
# Percentage of 18-64 population who see good opportunities to start a firm in the area where they live


# Remove X's in PerceivedOpportunities year columns
names(PerceivedOpportunities) <- gsub("X", "", names(PerceivedOpportunities))


# Change years from columns to rows and create CPreceivedOpportunities
CPerceivedOpportunities<- melt(data = PerceivedOpportunities,
                  id.vars = c("Country"),
                  measure.vars = c("2001", "2002", "2003", "2004", "2005", "2006",
                                   "2007", "2008", "2009", "2010", "2011", "2012",
                                   "2013"))


# Rename columns
CPerceivedOpportunities <- plyr::rename(x = CPerceivedOpportunities, 
                                      replace = c("variable" = "Year",
                                                  "value" = "PercentOpportunities"))



########## Clean Annual GEM NES Datasets ##########

# Draw out Country and D01 only
Clean01 <- GEM2001[,c("country", "ki01d01")]
Clean02 <- GEM2002[,c("country", "ki02d01")]
Clean03 <- GEM2003[,c("country", "ki03d01")]
Clean04 <- GEM2004[,c("ki04ctry", "ki04d01")]
Clean05 <- GEM2005[,c("KI05ctry", "KI05D01")]
Clean06 <- GEM2006[,c("KI06CTRY", "KI06D01_mean")]
Clean07 <- GEM2007[,c("ki07ctry", "ki07d01_")]
Clean08 <- GEM2008[,c("NES08COUNTRY", "NES08_D01_MEAN")]
Clean09 <- GEM2009[,c("NES09COUNTRY", "NES09_D01_MEAN")]
Clean10 <- GEM2010[,c("NES10CRNAME", "NES10_D01_MEAN")]

remove(GEM2001, GEM2002, GEM2003, GEM2004, GEM2005, GEM2006, GEM2007, GEM2008, GEM2009, GEM2010)


# Edit column names for each dataframe
Clean01 <- plyr::rename(x = Clean01, 
                                      replace = c("ki01d01" = "Year01",
                                                  "country" = "Country"))

Clean02 <- plyr::rename(x = Clean02, 
                                      replace = c("ki02d01" = "Year02",
                                                  "country" = "Country"))

Clean03 <- plyr::rename(x = Clean03, 
                                      replace = c("ki03d01" = "Year03",
                                                  "country" = "Country"))

Clean04 <- plyr::rename(x = Clean04, 
                                      replace = c("ki04d01" = "Year04",
                                                  "ki04ctry" = "Country"))

Clean05 <- plyr::rename(x = Clean05, 
                                      replace = c("KI05D01" = "Year05",
                                                  "KI05ctry" = "Country"))

Clean06 <- plyr::rename(x = Clean06, 
                                      replace = c("KI06D01_mean" = "Year06",
                                                  "KI06CTRY" = "Country"))

Clean07 <- plyr::rename(x = Clean07, 
                                      replace = c("ki07d01_" = "Year07",
                                                  "ki07ctry" = "Country"))

Clean08 <- plyr::rename(x = Clean08, 
                                      replace = c("NES08_D01_MEAN" = "Year08",
                                                  "NES08COUNTRY" = "Country"))

Clean09 <- plyr::rename(x = Clean09, 
                                      replace = c("NES09_D01_MEAN" = "Year09",
                                                  "NES09COUNTRY" = "Country"))

Clean10 <- plyr::rename(x = Clean10, 
                                      replace = c("NES10_D01_MEAN" = "Year10",
                                                  "NES10CRNAME" = "Country"))


#### Merge Annual GEM data 

MergedGEM <- merge(CCurrentOwner, CEntreIntention,
                   union("Country", "Year"),
                   all = TRUE)

MergedGem2 <- merge(CFearFail, CNascentEntre,
                   union("Country", "Year"),
                   all = TRUE) 

MergedGem3 <- merge(CPerceivedCapabilities, MergedGEM,
                   union("Country", "Year"),
                   all = TRUE) 

MergedGem4 <- merge(MergedGem2, MergedGem3,
                   union("Country", "Year"),
                   all = TRUE) 

FinalGEM <- merge(MergedGem4, CPerceivedOpportunities,
                   union("Country", "Year"),
                   all = TRUE)


# Convert percent columns from character to numeric
FinalGEM[,"PercentPerceived"] <- as.numeric(FinalGEM[,"PercentPerceived"])
FinalGEM[,"PercentFear"] <- as.numeric(FinalGEM[,"PercentFear"])
FinalGEM[,"PercentNascent"] <- as.numeric(FinalGEM[,"PercentNascent"])
FinalGEM[,"PercentOwner"] <- as.numeric(FinalGEM[,"PercentOwner"])
FinalGEM[,"PercentIntention"] <- as.numeric(FinalGEM[,"PercentIntention"])
FinalGEM[,"PercentOpportunities"] <- as.numeric(FinalGEM[,"PercentOpportunities"])



# Remove unncessary data from environment
remove(CCurrentOwner, CEntreIntention, CFearFail, CNascentEntre, CPerceivedCapabilities, CPerceivedOpportunities, CurrentOwner, EntreIntention, FearFail, MergedGEM, MergedGem2, MergedGem3, MergedGem4, PerceivedCapabilities, PerceivedOpportunities, NascentEntre)



####### Import tempfix for GEM data (created this by copying data frame (extra code for generating data frame is in misc/TrialFile.Rmd), editing outide R, and saving .csv in repository)

GEMAnnualData <- repmis::source_data("https://github.com/SamDund/Assign2Education/raw/master/GEMData/Gemyears.csv", header = TRUE, cache = FALSE) 


##### Clean and merge tempfix GEM Data ####

# Change column names
names(GEMAnnualData) <- gsub("Year01", "2001", names(GEMAnnualData))
names(GEMAnnualData) <- gsub("Year02", "2002", names(GEMAnnualData))
names(GEMAnnualData) <- gsub("Year03", "2003", names(GEMAnnualData))
names(GEMAnnualData) <- gsub("Year04", "2004", names(GEMAnnualData))
names(GEMAnnualData) <- gsub("Year05", "2005", names(GEMAnnualData))
names(GEMAnnualData) <- gsub("Year06", "2006", names(GEMAnnualData))
names(GEMAnnualData) <- gsub("Year07", "2007", names(GEMAnnualData))
names(GEMAnnualData) <- gsub("Year08", "2008", names(GEMAnnualData))
names(GEMAnnualData) <- gsub("Year09", "2009", names(GEMAnnualData))
names(GEMAnnualData) <- gsub("Year10", "2010", names(GEMAnnualData))


# Change years from columns to rows and create CleanGEM
CleanGEM <- melt(data = GEMAnnualData,
                 id.vars = c("Country"),
                 measure.vars = c("2001", "2002", "2003", "2004", "2005", "2006",
                                   "2007", "2008", "2009", "2010"))

# Rename columns
CleanGEM <- plyr::rename(x = CleanGEM,
                         replace = c("variable" = "Year",
                                     "value" = "WayofTeach"))

# Merge Clean CleanGEM with FinalGEM 
CompleteData <- merge(CleanGEM, FinalGEM,
                   union("Country", "Year"),
                   all = TRUE)

write.csv(CompleteData, file = "CompleteData.csv")

# Remove unncessary data from environment
remove(CCurrentOwner, CEntreIntention, CFearFail, CNascentEntre, CPerceivedCapabilities, CPerceivedOpportunities, CurrentOwner, EntreIntention, FearFail, MergedGEM, MergedGem2, MergedGem3, MergedGem4, PerceivedCapabilities, PerceivedOpportunities, NascentEntre, Clean01, Clean02, Clean03, Clean04, Clean05, Clean06, Clean07, Clean08, Clean09, Clean10, CleanGEM, FinalGEM, GEMAnnualData, SupportiveTeaching)

```

